extends TextureButton


# Called when the node enters the scene tree for the first time.
func _ready():
	# Connect the pressed signal to the _on_Button_pressed function
	self.connect("pressed", Callable(self, "_on_Button_pressed"))
	

		

func _process(delta):
		#Checks if the texture needs to be set
	if Global.texture_member5:
		self.texture_normal = Global.texture_member5

# Function to handle the button press
func _on_Button_pressed():
	
	get_tree().change_scene_to_file("res://teamSelection.tscn")
	
	Global.currentMemberSelected = 4
	
	Global.teamScreenVisible = false

	Global.teamSelectionVisible = true
	

#Function to set texture of the button
